# Generated by Django 4.1.7 on 2023-04-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('heading0', models.CharField(default='', max_length=500)),
                ('content_heading0', models.CharField(default='', max_length=5000)),
                ('heading1', models.CharField(default='', max_length=500)),
                ('content_heading1', models.CharField(default='', max_length=5000)),
                ('heading2', models.CharField(default='', max_length=500)),
                ('content_heading2', models.CharField(default='', max_length=5000)),
                ('publishing_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
